[package]
name = "cryptopals-solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
base64_light = "0.1.5"
character_frequency = "0.2.0"
openssl = "0.10.54"